import { Router } from 'express';
import authRoutes from './modules/auth/auth.routes';
import walletRoutes from './modules/wallet/wallet.routes';
import beneficiaryRoutes from './modules/beneficiaries/beneficiaries.routes';
import dmtRoutes from './modules/dmt/dmt.routes';
import bbpsRoutes from './modules/bbps/bbps.routes';
import rechargeRoutes from './modules/recharge/recharge.routes';
import payoutRoutes from './modules/payout/payout.routes';
import pgRoutes from './modules/payment-gateway/pg.routes';
import aepsRoutes from './modules/aeps/aeps.routes';
import cmsRoutes from './modules/cms/cms.routes';
import cardSwipeRoutes from './modules/card-swipe/card-swipe.routes';
import upiRoutes from './modules/upi/upi.routes';
import matmRoutes from './modules/matm/matm.routes';
import aadhaarPayRoutes from './modules/aadhaar-pay/aadhaar-pay.routes';
import panCardRoutes from './modules/pan-card/pan-card.routes';
import walletTransferRoutes from './modules/wallet-transfer/wallet-transfer.routes';
import travelRoutes from './modules/travel/travel.routes';
import insuranceRoutes from './modules/insurance/insurance.routes';
import kycRoutes from './modules/kyc/kyc.routes';
import networkRoutes from './modules/network/network.routes';
import adminRoutes from './modules/admin/admin.routes';
import transactionRoutes from './modules/transactions/transactions.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/wallet', walletRoutes);
router.use('/beneficiaries', beneficiaryRoutes);
router.use('/dmt', dmtRoutes);
router.use('/bbps', bbpsRoutes);
router.use('/recharge', rechargeRoutes);
router.use('/payout', payoutRoutes);
router.use('/payment-gateway', pgRoutes);
router.use('/aeps', aepsRoutes);
router.use('/cms', cmsRoutes);
router.use('/card-swipe', cardSwipeRoutes);
router.use('/upi', upiRoutes);
router.use('/matm', matmRoutes);
router.use('/aadhaar-pay', aadhaarPayRoutes);
router.use('/pan-card', panCardRoutes);
router.use('/wallet-transfer', walletTransferRoutes);
router.use('/travel', travelRoutes);
router.use('/insurance', insuranceRoutes);
router.use('/transactions', transactionRoutes);
router.use('/kyc', kycRoutes);
router.use('/network', networkRoutes);
router.use('/admin', adminRoutes);

export default router;
